# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = "../c\ primr\ plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/diceroll.o" "../c\ primr\ plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/manydice.o"
LINKOBJ  = "../c primr plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/diceroll.o" "../c primr plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/manydice.o"
LIBS     = -L"D:/c/Dev-Cpp/MinGW64/lib" -L"D:/c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/c/Dev-Cpp/MinGW64/include" -I"D:/c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/c/Dev-Cpp/MinGW64/include" -I"D:/c/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/c/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 项目1.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

"../c\ primr\ plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/diceroll.o": ../c\ primr\ plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/diceroll.c
	$(CPP) -c "../c primr plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/diceroll.c" -o "../c primr plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/diceroll.o" $(CXXFLAGS)

"../c\ primr\ plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/manydice.o": ../c\ primr\ plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/manydice.c
	$(CPP) -c "../c primr plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/manydice.c" -o "../c primr plus/资源/9780321928429_CPrimerPlus6E_code/Ch12/manydice.o" $(CXXFLAGS)
